/*
# [PUBLIC] ACME.ACME_BI.V_FACT_AGGR_SALES_STORE_DAY

Vista pública sobre ACME.ACME_BI_DATA.FACT_AGGR_SALES_STORE_DAY para el informe de PowerBI.
Debe aplicar seguridad a nivel de fila usando PLATFORM.GOVERNANCE.V_STORE_ACCESS.


*/

CREATE OR REPLACE VIEW ACME.ACME_BI.V_FACT_AGGR_SALES_STORE_DAY
AS
    SELECT 
    f.ID_DATE,
    f.ID_STORE,
    f.ID_SECTION,
    f.SOLD_UNITS,
    f.NET_AMOUNT

    FROM ACME.ACME_BI_DATA.FACT_AGGR_SALES_STORE_DAY f 
    INNER JOIN PLATFORM.GOVERNANCE.V_STORE_ACCESS g 
    ON g.id_store=f.id_store
;

