/*
## ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY

Procedimiento que agrega las ventas y las carga de forma INCREMENTAL en
ACME.ACME_BI_DATA.FACT_AGGR_SALES_STORE_DAY.



### Reglas de negocio
- NET_AMOUNT = GROSS_AMOUNT - DISCOUNT_AMOUNT.
- Excluir ventas de tiendas cerradas (ID_STORE_STATUS <> 1).

##Versiones
17-09-2026 : Versión Inicial

*/

CREATE OR REPLACE PROCEDURE ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS

$$
DECLARE
    EVENT_ID    NUMBER  DEFAULT 0;
    ROWS_MERGED NUMBER  DEFAULT 0;
    TASK_NAME   VARCHAR DEFAULT 'TSK_LOAD_FACT_AGGR_SALES_STORE_DAY';
BEGIN

    CALL PLATFORM.GOVERNANCE.P_ETL_EVENT_START('ACME.ACME_BI_DATA.FACT_AGGR_SALES_STORE_DAY');
    SELECT $1 INTO :EVENT_ID FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

    BEGIN TRANSACTION;

    MERGE INTO ACME.ACME_BI_DATA.FACT_AGGR_SALES_STORE_DAY trg
    USING( 
        select 
            s.SALE_DATE AS ID_DATE,
            s.ID_STORE AS ID_STORE,
            a.ID_SECTION AS ID_SECTION,
            SUM(s.SOLD_UNITS) AS SOLD_UNITS,
            SUM(s.GROSS_AMOUNT-s.DISCOUNT_AMOUNT) AS NET_AMOUNT
        FROM ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE s
        INNER JOIN RETAIL_LAKE.SALES_SHARING.DIM_ARTICLE a
            ON a.ID_ARTICLE=s.ID_ARTICLE
        INNER JOIN RETAIL_LAKE.SALES_SHARING.DIM_STORE st
            ON st.ID_STORE= s.ID_STORE AND st.ID_STORE_STATUS=1
        WHERE s.METADATA$ACTION='INSERT'
        GROUP BY 1,2,3
    ) src
    ON trg.ID_DATE=src.ID_DATE
    AND trg.ID_STORE=src.ID_STORE
    AND trg.ID_SECTION=src.ID_SECTION

    WHEN MATCHED THEN UPDATE SET
    trg.SOLD_UNITS=trg.SOLD_UNITS + src.SOLD_UNITS,
    trg.NET_AMOUNT=trg.NET_AMOUNT + src.NET_AMOUNT 

    WHEN NOT MATCHED THEN INSERT (ID_DATE, ID_STORE, ID_SECTION, SOLD_UNITS, NET_AMOUNT) VALUES ( src.ID_DATE, src.ID_STORE, src.ID_SECTION, src.SOLD_UNITS, src.NET_AMOUNT );

    ROWS_MERGED:=SQLROWCOUNT;

    COMMIT;
    
    CALL PLATFORM.GOVERNANCE.P_ETL_EVENT_END(
    :EVENT_ID, :TASK_NAME, 'SUCCESS', :ROWS_MERGED, 'CARGA INCREMENTAL EXITOSA');
    
        RETURN 'Proceso exitoso, filas : '|| :ROWS_MERGED;

    EXCEPTION 
        WHEN OTHER THEN 
            ROLLBACK;

        CALL PLATFORM.GOVERNANCE.P_ETL_EVENT_END(
            :EVENT_ID, :TASK_NAME, 'FAILED', :ROWS_MERGED, 'ERROR EN LA CARGA');
            
        RAISE;
END;
$$

;
