/*
# ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE

STREAM (CDC) sobre RETAIL_LAKE.SALES_SHARING.SALES_TICKET_LINE.
Captura las nuevas líneas de ticket y se usa como disparador de la carga (SYSTEM$STREAM_HAS_DATA).


##Versiones
17-09-2026 : Versión Inicial
*/

CREATE OR REPLACE STREAM ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE
          ON TABLE RETAIL_LAKE.SALES_SHARING.SALES_TICKET_LINE
          APPEND_ONLY = TRUE;
