/*
## ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY

Task que orquesta la carga del FACT de ventas.

--##Versiones
--18-09-2026 : Versión Inicial

*/

ALTER TASK IF EXISTS ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY SUSPEND;

CREATE OR REPLACE TASK  ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY

    WAREHOUSE= ACME_PIPELINE_WH
    SCHEDULE= 'USING CRON 0 7 * * * Europe/Madrid '
    WHEN SYSTEM$STREAM_HAS_DATA ('ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE')
AS 
    CALL ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY();


ALTER TASK IF EXISTS ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY RESUME;

ALTER TASK IF EXISTS ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY_RELAUNCHED SUSPEND;

CREATE OR REPLACE TASK ACME.ACME_BI_DATA.TSK_LOAD_FACT_AGGR_SALES_STORE_DAY_RELAUNCHED
    WAREHOUSE=ACME_PIPELINE_WH
AS 
    CALL ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY();




