SELECT SYSTEM$STREAM_HAS_DATA('ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE');

CALL ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY();

SELECT SYSTEM$STREAM_HAS_DATA('ACME.ACME_BI_DATA.STR_SALES_TICKET_LINE');

SELECT * FROM ACME.ACME_BI.V_FACT_AGGR_SALES_STORE_DAY ORDER BY ID_DATE, ID_STORE, ID_SECTION;


SELECT * FROM PLATFORM.GOVERNANCE.ETL_EVENT_LOG ORDER BY EVENT_ID DESC;

INSERT INTO RETAIL_LAKE.SALES_SHARING.SALES_TICKET_LINE
    (ID_TICKET, ID_TICKET_LINE, ID_STORE, ID_ARTICLE, SALE_DATE, SOLD_UNITS, GROSS_AMOUNT, DISCOUNT_AMOUNT)
VALUES (900010, 1, 1001, 5001, '2026-06-03', 1, 19.95, 0.00);
CALL ACME.ACME_BI_DATA.PR_FACT_AGGR_SALES_STORE_DAY();

SELECT * FROM PLATFORM.GOVERNANCE.ETL_EVENT_LOG ORDER BY EVENT_ID DESC;
